// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhHBPaR78avzMkVM4mii6ktcowXtgyE6Q',
    appId: '1:915049198878:web:b8d5edea1ee2797e7f050f',
    messagingSenderId: '915049198878',
    projectId: 'merchant-app-uae',
    authDomain: 'merchant-app-uae.firebaseapp.com',
    storageBucket: 'merchant-app-uae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiGSn8-hLb7nuRfGpjEBDlUhx0j0TGJBo',
    appId: '1:915049198878:android:817a1bfdce01ca967f050f',
    messagingSenderId: '915049198878',
    projectId: 'merchant-app-uae',
    storageBucket: 'merchant-app-uae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAvcj3OHc_jhXXbc_BBZwDtxwPOVa9qFA',
    appId: '1:915049198878:ios:55daac047618204f7f050f',
    messagingSenderId: '915049198878',
    projectId: 'merchant-app-uae',
    storageBucket: 'merchant-app-uae.firebasestorage.app',
    iosBundleId: 'ae.pay10.merchant.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAvcj3OHc_jhXXbc_BBZwDtxwPOVa9qFA',
    appId: '1:915049198878:ios:c9e442a848db03397f050f',
    messagingSenderId: '915049198878',
    projectId: 'merchant-app-uae',
    storageBucket: 'merchant-app-uae.firebasestorage.app',
    iosBundleId: 'com.example.merchantapp',
  );
}
